apiVersion: v1
kind: Service

metadata:
  name: home-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: home

  ports:
  - port: {{ .Values.home.service.port }}
    targetPort: {{ .Values.home.service.targetPort }}

  type: ClusterIP
