apiVersion: v1
kind: Service

metadata:
  name: fetch-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: fetch

  ports:
  - port: {{ .Values.fetch.service.port }}
    targetPort: {{ .Values.fetch.service.targetPort }}

  type: ClusterIP
